apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thefirewall.serviceAccountName" . }}
  namespace: default  # Change to your desired namespace
automountServiceAccountToken: true  # Set to false if you don't want to auto-mount the token